version: '3'
services:
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      TZ: 'Asia/Tokyo'
    volumes:
      - db-storage:/var/lib/mysql
  remix:
    build: .
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL
      - SESSION_SECRET
      - APP_URL
    ports:
      - 3000:3000
      - 5555:5555
      - 8002:8002
      - 9323:9323 # playwright reporter
    volumes:
      - ./.env:/app/.env
    depends_on:
      - mysql

volumes:
  db-storage:
