version: '3'
services:
  prod:
    build: .
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL
      - SESSION_SECRET
      - APP_URL
    ports:
      - 3000:3000
      - 5555:5555
  dev:
    image: node:18.14.0
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL
      - SESSION_SECRET
      - APP_URL
    ports:
      - 3000:3000
      - 5555:5555
      - 8080:8080 # remix DevTools websocket server
    volumes:
      - .:/8bit-stack
    working_dir: /8bit-stack
    command: bash
  validate:
    image: mcr.microsoft.com/playwright:v1.35.0-jammy
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL
      - SESSION_SECRET
      - APP_URL
    volumes:
      - .:/8bit-stack
    ports:
      - 3000:3000
      - 5555:5555
      - 8080:8080 # remix DevTools websocket server
      - 9323:9323 # playwright reporter
    working_dir: /8bit-stack
    command: npm run validate
