version: '3'
services:
  remix-dev:
    image: node:18.14.0-slim
    platform: linux/amd64
    environment:
      - HOST=0.0.0.0
    ports:
      - 3000:3000
      - 5555:5555
      - 8002:8002
      - 9323:9323 # playwright reporter
    volumes:
      - .:/8bit-stack
    working_dir: /8bit-stack
    command: bash
    depends_on:
      - mysql
